print('                          Asiri Hospital Ltd                    ')
print('                      ========================')
print('Information Confirm List')
print('-'*60)
name=input('What is your name?')
print()
address=input('What is your address?')
print()
age=input('What is your age?')
print()
Tel=input('What is your Telephone no?')
print()
fasting=input('When did you start fasting?')
print()
print('*'*60)
print('Your name is'+ name)
print('Your address is'+ address)
print('Your age is'+ age)
print('Your Telephone no is'+ Tel)
print('Your fasting status'+ fasting)
print()
print(name+' You can start taking your test in lab no 2 now.your age is'+age)
print('Please proceed',"Welcome to Asiri Hospital Ltd ",sep=" ! ",end=" Thank you for choosing Asiri")
